//! SeaORM Entity. Generated by sea-orm-codegen 0.2.6

pub use super::ingredient::Entity as Ingredient;
pub use super::ingredient_tag::Entity as IngredientTag;
pub use super::recipe::Entity as Recipe;
pub use super::recipe_ingredient::Entity as RecipeIngredient;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
