# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "aurelia"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "aurelia"
path = "src/main.rs"

# [[bin]]
# name = "migrate"
# path = "src/migrate.rs"

[[bin]]
name = "cli"
path = "src/cli.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
axum = "0.2.3"
barrel = { version = "0.6", features = ["pg"] }
config = "0.11"
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
fast_log = "1.3"
futures = "0.3"
hyper = "0.14"
jsonwebtoken = "7"
openidconnect = "2"
rbatis = { version = "2.0", default-features = false, features = [
    "tokio1",
    "postgres",
] }
refinery = { version = "0.6", features = ["tokio-postgres", "tokio"] }
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-bunyan-formatter = "0.2"
tracing-log = "0.1"
tracing-subscriber = "0.2"
tower = "0.4"
uuid = { version = "0.8", features = ["v4", "serde"] }
sql-press = { version = "0.1", path = "../sql-press" }

[dev-dependencies]
lazy_static = "1.4"
once_cell = "1.8"