# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "aurelia"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "aurelia"
path = "src/main.rs"

# [[bin]]
# name = "migrate"
# path = "src/migrate.rs"

[[bin]]
name = "cli"
path = "src/cli.rs"

[dependencies]
anyhow = "1.0"
axum = "0.2.3"
barrel = { version = "0.6", features = ["pg"] }
config = "0.11"
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
fast_log="1.3"
futures = "0.3"
jsonwebtoken = "7"
rbatis =  { version = "2.0", default-features = false, features = ["tokio1", "postgres"] }
refinery = { version = "0.6", features = ["tokio-postgres", "tokio"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"
tower = "0.4"
uuid = { version = "0.8", features = ["v4", "serde"] }