[http]
address = "127.0.0.1"
port = 3001

[database]
host = "localhost"
port = 5432
database_name = "realizor"
username = "realizor"
password = "realizor"

[application]

[application.auth]
jwt_secret = "TQgF1LMRwGVyH4XLZhak3hnlvxVCtWuuCY0E8GwcEdZpds2vBe5F47U3wEij32sPqu7va7g8rIVj5aoaxQKnzYEd8eobhcjmKjUcGNRzPEYZ4CwJEOMlcAck"
# expiration offset in seconds
jwt_expiration_offset_seconds = 1000000
jwt_header_name = "authorization"
path_prefix = "/auth"

[application.auth.oidc.sh_stage]
provider_name = "sh_stage"
client_name = "tim-test"
client_id = "00fd8bd0-c1df-4efa-9cea-584effa2db94"
client_secret = "sy85cgPqpL5Q4rm"
client_scopes = ["openid"]
client_role = "web"
issuer_url = "https://aaa.mew-tech.io/op"
redirect_url = "http://localhost:3000/auth/oidc_login_cb/sh_stage"
