[http]
address = "127.0.0.1"
port = 3001

[database]
host = "localhost"
port = 5430
database_name = "aurelia"
username = "aurelia"
password = "aurelia"

[application]
debug = true

[application.auth]
jwt_secret = "TQgF1LMRwGVyH4XLZhak3hnlvxVCtWuuCY0E8GwcEdZpds2vBe5F47U3wEij32sPqu7va7g8rIVj5aoaxQKnzYEd8eobhcjmKjUcGNRzPEYZ4CwJEOMlcAck"
jwt_expiration_offset_seconds = 1000000
jwt_header_name = "authorization"
jwt_cookie_name = "id_token"
path_prefix = "/auth"

[application.auth.oidc.sh_stage]
provider_name = "sh_stage"
client_name = "nutrist"
client_id = "0aa14c41-fa14-45cd-84a1-9ea63c0b9d80"
client_secret = "sy85cgPqpL5Q4rm!"
client_scopes = ["openid"]
client_role = "web"
issuer_url = "https://aaa.mew-tech.io/op"
redirect_url = "http://localhost:3001/auth/oidc_login_cb/sh_stage"
