[http]
address = "127.0.0.1"
port = 3001
base_url = "http://localhost"

[database]
host = "localhost"
port = 5430
database_name = "aurelia"
username = "aurelia"
password = "aurelia"

[application]
debug = true

[application.auth]
jwt_secret = "TQgF1LMRwGVyH4XLZhak3hnlvxVCtWuuCY0E8GwcEdZpds2vBe5F47U3wEij32sPqu7va7g8rIVj5aoaxQKnzYEd8eobhcjmKjUcGNRzPEYZ4CwJEOMlcAck"
jwt_expiration_offset_seconds = 1000000
jwt_header_name = "authorization"
jwt_cookie_name = "id_token"
jwt_algorithm = "RS256"
jwtrsaprivatekey = "comes_from_dotenv"
jwtrsapublickey = "comes_from_dotenv"
path_prefix = "/auth"
redirect_on_login_success = "/"
redirect_on_login_error = "/login/error"
login_path = "/login"

[application.auth.oidc.auth0]
provider_name = "auth0"
client_name = "nutrist"
client_id = "***"
client_secret = "***"
client_scopes = ["openid email profile"]
client_role = "web"
issuer_url = "https://nutrist.eu.auth0.com/"
redirect_url = "http://nutrist.test:3001/auth/oidc_login_cb/auth0"

[application.custom]