[http]
address = "127.0.0.1"
port = 3000

[database]
host = "localhost"
port = 5432
database_name = "realizor"
username = "realizor"
password = "realizor"

[application]

[application.auth]
jwt_secret = "TQgF1LMRwGVyH4XLZhak3hnlvxVCtWuuCY0E8GwcEdZpds2vBe5F47U3wEij32sPqu7va7g8rIVj5aoaxQKnzYEd8eobhcjmKjUcGNRzPEYZ4CwJEOMlcAck"
# expiration offset in seconds
jwt_expiration_offset_seconds = 1000000
jwt_header_name = "authorization"
path_prefix = "/auth"
